const api = require('../../services/staff-api')
const labels = {pending:'待确认',confirmed:'已确认',cancelled:'已取消',waitlisted:'候补',completed:'已结束',open:'报名中',in_progress:'开课中',paid:'已收款',unpaid:'待收款'}
const decorate = rows => rows.map(r=>({...r,statusText:labels[r.registrationStatus||r.status]||r.registrationStatus||r.status,paymentText:labels[r.paymentStatus]||r.paymentStatus}))
Page({
 data:{paymentMethods:['微信扫码','支付宝扫码','银行转账','现金','其他'],paymentMethodIndex:0,view:'desk',rows:[],people:[],suggestions:[],interviews:[],sessions:[],roster:[],images:[],profile:{},form:{nickname:'',realName:'',city:'上海',birthMonth:'',referralSource:'',content:''},tab:'timeline',filter:'all',loading:true,canOperate:false,canPayment:false},
 onLoad(o){this.setData({view:o.view||'desk',id:o.id||'',filter:o.filter||'all'});this.requestId='staff-'+Date.now()+'-'+Math.random().toString(36).slice(2)},
 onShow(){this.refresh()},
 async refresh(){this.setData({loading:true,error:''});try{const me=await api.request('/me');this.setData({me,canOperate:!!Number(me.can_operate),canPayment:!!Number(me.can_payment)});const v=this.data.view,id=encodeURIComponent(this.data.id);
 if(v==='desk'||v==='sessions'||v==='history'){const sessions=decorate(await api.request('/sessions?history='+(v==='history')));this.setData({sessions});if(v!=='history'&&sessions.length){const roster=decorate(await api.request('/sessions/'+sessions[0].id+'/registrations'));this.setData({roster:roster.filter(r=>r.registrationStatus!=='cancelled'),allCount:roster.filter(r=>r.registrationStatus!=='cancelled').length,pendingCount:roster.filter(r=>r.registrationStatus==='pending').length,unpaidCount:roster.filter(r=>r.registrationStatus!=='cancelled'&&r.paymentStatus==='unpaid').length})}else this.setData({roster:[]});if(v==='desk')this.setData({interviews:await api.request('/interviews')})}
 if(v==='people')this.setData({people:await api.request('/people')});
 if(v==='profile'){const profile=await api.request('/people/'+id);profile.activities=decorate(profile.activities||[]);this.setData({profile,interviews:profile.interviews||[]})}
 if(v==='roster'){let rows=decorate(await api.request('/sessions/'+id+'/registrations'));rows=rows.filter(r=>r.registrationStatus!=='cancelled');if(this.data.filter==='pending')rows=rows.filter(r=>r.registrationStatus==='pending');if(this.data.filter==='unpaid')rows=rows.filter(r=>r.paymentStatus==='unpaid');this.setData({rows})}
 if(v==='interviews')this.setData({interviews:await api.request('/interviews')});
 if(v==='interview'){const people=await this.formPeople();this.setData({people,personIndex:Math.max(0,people.findIndex(p=>p.id===(this.data.selectedPerson||this.data.id))),selectedPerson:this.data.selectedPerson||this.data.id||people[0]?.id||''})}
 if(v==='enroll'){const [people,sessions]=await Promise.all([this.formPeople(),api.request('/sessions')]);this.setData({people,sessions,personIndex:Math.max(0,people.findIndex(p=>p.id===(this.data.selectedPerson||this.data.id))),selectedPerson:this.data.selectedPerson||this.data.id||people[0]?.id||'',selectedSession:sessions[0]?.id||''})}
 if(v==='registration'||v==='payment'){const registration=await api.request('/registrations/'+id);if(!registration)throw new Error('报名不存在');this.setData({registration:{...registration,statusText:labels[registration.registrationStatus],paymentText:labels[registration.paymentStatus]},attendance:await api.request('/registrations/'+id+'/attendance')})}
 }catch(e){this.setData({error:e.message});if(e.code===401||e.code===403)this.setData({me:null,rows:[],people:[],interviews:[],profile:{},roster:[],sessions:[],suggestions:[]})}finally{this.setData({loading:false})}},
 async formPeople(){const people=await api.request('/people');const selected=this.data.selectedPerson||this.data.id;if(selected&&!people.some(p=>p.id===selected))people.unshift(await api.request('/people/'+encodeURIComponent(selected)));return people},
 async arrive(e){const dayId=e.currentTarget.dataset.id;wx.showModal({title:'登记当天到场',content:'仅记录当天到场，不代表整期完成。',success:async r=>{if(!r.confirm)return;try{await api.request('/registrations/'+this.data.id+'/arrival','PUT',{dayId});this.refresh()}catch(e){this.fail(e)}}})},
 cancel(){wx.showModal({title:'取消未结算报名',content:'保留原报名记录。已结算或整单报名需在后台核对处理。',success:async r=>{if(!r.confirm)return;try{await api.request('/registrations/'+this.data.id+'/cancel','PUT');this.refresh()}catch(e){this.fail(e)}}})},
 go(e){const d=e.currentTarget.dataset;wx.navigateTo({url:'/staff/workspace/index?view='+d.view+'&id='+encodeURIComponent(d.id||'')+'&filter='+(d.filter||'all')})},
 root(e){wx.redirectTo({url:'/staff/workspace/index?view='+e.currentTarget.dataset.view})},
 returnMine(){wx.switchTab({url:'/pages/mine/index'})},
 setTab(e){this.setData({tab:e.currentTarget.dataset.tab})},
 field(e){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value})},
 async search(e){const q=e.detail.value.trim();this.setData({searchQuery:q,searchEmpty:false});const seq=(this.searchSeq||0)+1;this.searchSeq=seq;if(!q){this.setData({suggestions:[]});return}try{const suggestions=await api.request('/people?q='+encodeURIComponent(q)+'&limit=5');if(this.searchSeq===seq)this.setData({suggestions,searchEmpty:!suggestions.length})}catch(e){if(this.searchSeq===seq){this.setData({suggestions:[]});this.fail(e)}}},
 selectPaymentMethod(e){this.setData({paymentMethodIndex:Number(e.detail.value)})},
 selectPerson(e){this.setData({selectedPerson:this.data.people[Number(e.detail.value)].id,personIndex:Number(e.detail.value)})},
 selectSession(e){this.setData({selectedSession:this.data.sessions[Number(e.detail.value)].id,sessionIndex:Number(e.detail.value)})},
 fail(e){wx.showToast({title:e.message||'操作失败，请重试',icon:'none'})},
 async saveCustomer(){if(this.data.saving)return;this.setData({saving:true});try{const r=await api.request('/people','POST',this.data.form);wx.redirectTo({url:'/staff/workspace/index?view=profile&id='+r.id})}catch(e){this.fail(e)}finally{this.setData({saving:false})}},
 async enroll(){if(this.data.saving)return;this.setData({saving:true});try{await api.request('/registrations','POST',{customerId:this.data.selectedPerson,sessionId:this.data.selectedSession});wx.redirectTo({url:'/staff/workspace/index?view=roster&id='+this.data.selectedSession})}catch(e){this.fail(e)}finally{this.setData({saving:false})}},
 confirm(){wx.showModal({title:'确认报名',content:'确认报名不代表已付款。',success:async r=>{if(!r.confirm)return;try{await api.request('/registrations/'+this.data.id+'/confirm','PUT');this.refresh()}catch(e){this.fail(e)}}})},
 async pay(){if(this.data.saving)return;const amount=Number(this.data.form.amount);if(!Number.isFinite(amount)||amount<=0)return this.fail(new Error('请输入实际收款金额'));wx.showModal({title:'登记线下收款',content:'确认实际收到 ¥'+amount+'？不发起在线支付。',success:async r=>{if(!r.confirm)return;this.setData({saving:true});try{await api.request('/registrations/'+this.data.id+'/payment','PUT',{paymentStatus:'paid',amount,paymentMethod:['wechat_scan','alipay_scan','transfer','cash','other'][this.data.paymentMethodIndex],changeReason:this.data.form.paymentRemark||'工作人员移动工作台登记'});wx.navigateBack()}catch(e){this.fail(e)}finally{this.setData({saving:false})}}})},
 chooseImages(){wx.chooseMedia({count:6-this.data.images.length,mediaType:['image'],success:r=>{const images=this.data.images.concat(r.tempFiles.map(f=>({path:f.tempFilePath,size:f.size})));if(images.reduce((n,f)=>n+f.size,0)>2097152)return this.fail(new Error('图片合计请控制在2MB以内'));this.setData({images})}})},
 removeImage(e){this.setData({images:this.data.images.filter((_,i)=>i!==Number(e.currentTarget.dataset.index))})},
 async preview(e){try{wx.previewImage({urls:[await api.image(e.currentTarget.dataset.id)]})}catch(e){this.fail(e)}},
 async saveInterview(){if(this.data.saving)return;if(!this.data.form.content.trim()||!this.data.selectedPerson)return this.fail(new Error('请选择轻友并填写评价与感受'));this.setData({saving:true});try{const images=[];for(const im of this.data.images){const data=await api.encodeImage(im.path);images.push({data,mime:data.startsWith('/9j/')?'image/jpeg':'image/png'})}await api.request('/interviews','POST',{customerId:this.data.selectedPerson,content:this.data.form.content,images,requestId:this.requestId});wx.navigateBack()}catch(e){this.fail(e)}finally{this.setData({saving:false})}}
})
