<template>
  <div class="app-container">
    <el-alert title="卡次余额由不可变流水汇总；开户、增加和更正都会保留操作人、时间与原因，不直接覆盖余额。" type="info" :closable="false" show-icon class="mb20" />
    <el-form :inline="true"><el-form-item label="轻友"><el-select v-model="customerId" filterable clearable placeholder="全部轻友" size="small"><el-option v-for="item in customers" :key="item.id" :label="item.nickname + (item.realName ? '（' + item.realName + '）' : '')" :value="item.id" /></el-select></el-form-item><el-form-item><el-button type="primary" size="small" @click="load">查询</el-button></el-form-item></el-form>
    <el-button v-hasPermi="['life:pass:add']" type="primary" plain icon="el-icon-plus" size="mini" class="mb20" @click="showOpen">卡次开户</el-button>
    <el-table v-loading="loading" :data="rows">
      <el-table-column label="轻友" min-width="150"><template slot-scope="s"><div>{{ s.row.nickname }} <span class="muted">{{ s.row.realName || '' }}</span></div><div class="muted">{{ s.row.customerNo }}</div></template></el-table-column>
      <el-table-column prop="passType" label="卡次名称" min-width="150" />
      <el-table-column label="当前剩余" width="110"><template slot-scope="s"><strong>{{ s.row.balance }} 次</strong></template></el-table-column>
      <el-table-column label="状态" width="100"><template slot-scope="s"><el-tag size="mini" :type="Number(s.row.usable) ? 'success' : 'info'">{{ Number(s.row.usable) ? '可使用' : '不可用' }}</el-tag></template></el-table-column>
      <el-table-column label="有效期" min-width="180"><template slot-scope="s">{{ s.row.validFrom || '不限' }} 至 {{ s.row.validUntil || '长期' }}</template></el-table-column>
      <el-table-column label="操作" width="150"><template slot-scope="s"><el-button v-hasPermi="['life:pass:query']" type="text" @click="showLedger(s.row)">流水</el-button><el-button v-hasPermi="['life:pass:adjust']" type="text" @click="showAdjust(s.row)">调整</el-button></template></el-table-column>
    </el-table>
    <el-empty v-if="!loading && !rows.length" description="暂无卡次账户" />

    <el-dialog title="卡次开户" :visible.sync="openVisible" width="500px" append-to-body><el-form ref="openForm" :model="openForm" :rules="openRules" label-width="92px"><el-form-item label="轻友" prop="customerId"><el-select v-model="openForm.customerId" filterable style="width:100%"><el-option v-for="item in customers" :key="item.id" :label="item.nickname + (item.realName ? '（' + item.realName + '）' : '')" :value="item.id" /></el-select></el-form-item><el-form-item label="卡次名称" prop="passType"><el-input v-model="openForm.passType" maxlength="50" placeholder="例如：轻体营10次卡" /></el-form-item><el-form-item label="初始次数" prop="initialUnits"><el-input-number v-model="openForm.initialUnits" :min="1" :precision="0" style="width:100%" /></el-form-item><el-form-item label="有效期"><el-date-picker v-model="dates" type="daterange" value-format="yyyy-MM-dd" start-placeholder="开始日期" end-placeholder="结束日期" style="width:100%" /></el-form-item><el-form-item label="核验依据" prop="reason"><el-input v-model="openForm.reason" type="textarea" maxlength="500" placeholder="填写历史卡次表、购买记录或人工核验依据" /></el-form-item></el-form><div slot="footer"><el-button type="primary" :loading="saving" @click="submitOpen">确认开户</el-button><el-button @click="openVisible=false">取消</el-button></div></el-dialog>
    <el-dialog title="调整卡次" :visible.sync="adjustVisible" width="460px" append-to-body><el-alert :title="'当前剩余 ' + (selected.balance || 0) + ' 次；正数增加，负数扣减。'" type="warning" :closable="false" class="mb20" /><el-form ref="adjustForm" :model="adjustForm" :rules="adjustRules" label-width="86px"><el-form-item label="调整次数" prop="quantityDelta"><el-input-number v-model="adjustForm.quantityDelta" :precision="0" style="width:100%" /></el-form-item><el-form-item label="调整原因" prop="reason"><el-input v-model="adjustForm.reason" type="textarea" maxlength="500" /></el-form-item></el-form><div slot="footer"><el-button type="primary" :loading="saving" @click="submitAdjust">写入调整流水</el-button><el-button @click="adjustVisible=false">取消</el-button></div></el-dialog>
    <el-drawer :title="selected.passType + ' · 卡次流水'" :visible.sync="ledgerVisible" size="560px" append-to-body><div class="drawer"><el-empty v-if="!ledger.length" description="暂无流水"/><el-timeline><el-timeline-item v-for="item in ledger" :key="item.id" :timestamp="item.occurredAt"><div><strong>{{ label(item.entryType) }} {{ item.quantityDelta > 0 ? '+' : '' }}{{ item.quantityDelta }} 次</strong> · 余 {{ item.balanceAfter }} 次</div><div>{{ item.reason }}</div><div class="muted">{{ item.operatorName || '系统' }}<span v-if="item.sessionNumber"> · 第{{ item.sessionNumber }}期</span></div></el-timeline-item></el-timeline></div></el-drawer>
  </div>
</template>
<script>
import { listPass, getPassLedger, openPass, adjustPass } from '@/api/life/pass'
import { listCustomer } from '@/api/life/customer'
export default { name:'QlPass', data(){return{loading:false,saving:false,rows:[],customers:[],customerId:'',openVisible:false,adjustVisible:false,ledgerVisible:false,dates:[],selected:{},ledger:[],openForm:{},adjustForm:{},openRules:{customerId:[{required:true,message:'请选择轻友',trigger:'change'}],passType:[{required:true,message:'请填写卡次名称',trigger:'blur'}],initialUnits:[{required:true,message:'请填写初始次数',trigger:'change'}],reason:[{required:true,message:'请填写核验依据',trigger:'blur'}]},adjustRules:{quantityDelta:[{required:true,message:'请填写调整次数',trigger:'change'}],reason:[{required:true,message:'请填写调整原因',trigger:'blur'}]}}},created(){this.loadCustomers();this.load()},methods:{loadCustomers(){listCustomer({pageNum:1,pageSize:1000,status:'active'}).then(r=>{this.customers=r.rows||[]})},load(){this.loading=true;return listPass({customerId:this.customerId||undefined}).then(r=>{this.rows=r.data||[]}).finally(()=>{this.loading=false})},showOpen(){this.openForm={customerId:this.customerId||'',passType:'',initialUnits:1,reason:''};this.dates=[];this.openVisible=true},submitOpen(){this.$refs.openForm.validate(valid=>{if(!valid)return;this.saving=true;openPass({...this.openForm,validFrom:this.dates[0]||null,validUntil:this.dates[1]||null}).then(()=>{this.msgSuccess('卡次账户已建立');this.openVisible=false;this.load()}).finally(()=>{this.saving=false})})},showAdjust(row){this.selected=row;this.adjustForm={quantityDelta:0,reason:''};this.adjustVisible=true},submitAdjust(){this.$refs.adjustForm.validate(valid=>{if(!valid)return;if(!this.adjustForm.quantityDelta)return this.msgError('调整次数不能为0');this.saving=true;adjustPass(this.selected.id,this.adjustForm).then(()=>{this.msgSuccess('调整流水已写入');this.adjustVisible=false;this.load()}).finally(()=>{this.saving=false})})},showLedger(row){this.selected=row;this.ledger=[];this.ledgerVisible=true;getPassLedger(row.id).then(r=>{this.ledger=r.data||[]})},label(v){return({grant:'发放',consume:'使用',adjust:'调整',expire:'到期',void:'作废',refund:'退回'})[v]||v}}}
</script>
<style scoped>.muted{font-size:12px;color:#909399}.drawer{padding:20px}.mb20{margin-bottom:20px}</style>
