-- 轻生活运营系统核心业务表增量迁移 V1.1.0
-- 目标数据库：MySQL 8.0+
-- 前置条件：已导入原 lifestyle.sql，sys_user 等若依基础表存在。
-- 原则：只新增 ql_ 前缀表，不修改、删除旧表和旧数据。

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ql_schema_migration` (
  `version` varchar(32) NOT NULL,
  `description` varchar(255) NOT NULL,
  `executed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `executed_by` varchar(64) DEFAULT NULL,
  `file_sha256` char(64) DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='轻生活业务库迁移记录';

CREATE TABLE IF NOT EXISTS `ql_customer` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_no` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `nickname` varchar(50) NOT NULL,
  `real_name` varchar(50) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` varchar(16) NOT NULL DEFAULT 'unknown',
  `city` varchar(100) DEFAULT NULL,
  `first_source` varchar(32) NOT NULL DEFAULT 'unknown',
  `referrer_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `data_source` varchar(32) NOT NULL DEFAULT 'manual_entry',
  `data_confidence` varchar(16) NOT NULL DEFAULT 'unknown',
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `merged_into_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revision` int NOT NULL DEFAULT 0,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_customer_no` (`customer_no`),
  KEY `idx_ql_customer_nickname` (`nickname`),
  KEY `idx_ql_customer_real_name` (`real_name`),
  KEY `idx_ql_customer_referrer` (`referrer_customer_id`),
  CONSTRAINT `fk_ql_customer_referrer` FOREIGN KEY (`referrer_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_customer_merged` FOREIGN KEY (`merged_into_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_customer_gender` CHECK (`gender` IN ('female','male','other','unknown')),
  CONSTRAINT `ck_ql_customer_status` CHECK (`status` IN ('active','inactive','merged','deleted')),
  CONSTRAINT `ck_ql_customer_confidence` CHECK (`data_confidence` IN ('verified','probable','unknown')),
  CONSTRAINT `ck_ql_customer_not_self_ref` CHECK (`referrer_customer_id` IS NULL OR `referrer_customer_id` <> `id`),
  CONSTRAINT `ck_ql_customer_not_self_merge` CHECK (`merged_into_customer_id` IS NULL OR `merged_into_customer_id` <> `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='唯一轻友主档';

CREATE TABLE IF NOT EXISTS `ql_customer_identifier` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `identifier_type` varchar(32) NOT NULL,
  `identifier_value` varchar(255) NOT NULL,
  `normalized_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `display_hint` varchar(64) DEFAULT NULL,
  `app_scope` varchar(64) DEFAULT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `verification_status` varchar(16) NOT NULL DEFAULT 'unverified',
  `valid_from` datetime(3) DEFAULT NULL,
  `valid_to` datetime(3) DEFAULT NULL,
  `legacy_app_user_id` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_identifier_owner` (`customer_id`,`identifier_type`,`normalized_hash`),
  KEY `idx_ql_identifier_lookup` (`identifier_type`,`normalized_hash`),
  KEY `idx_ql_identifier_legacy_app_user` (`legacy_app_user_id`),
  CONSTRAINT `fk_ql_identifier_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_identifier_type` CHECK (`identifier_type` IN ('phone','wechat_openid','wechat_unionid','wechat_id','legacy_name','other')),
  CONSTRAINT `ck_ql_identifier_verify` CHECK (`verification_status` IN ('unverified','verified','conflict','expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='轻友身份线索；跨主档重复值由人工冲突流程处理';

CREATE TABLE IF NOT EXISTS `ql_session` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_number` int NOT NULL,
  `name` varchar(200) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `capacity` smallint unsigned NOT NULL DEFAULT 1,
  `standard_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `venue` varchar(200) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'draft',
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_session_number` (`session_number`),
  KEY `idx_ql_session_date` (`start_date`),
  CONSTRAINT `ck_ql_session_number` CHECK (`session_number` > 0),
  CONSTRAINT `ck_ql_session_dates` CHECK (`end_date` >= `start_date`),
  CONSTRAINT `ck_ql_session_capacity` CHECK (`capacity` > 0),
  CONSTRAINT `ck_ql_session_price` CHECK (`standard_price` >= 0),
  CONSTRAINT `ck_ql_session_status` CHECK (`status` IN ('draft','open','closed','in_progress','completed','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='一期连续活动对应一个唯一 Session';

CREATE TABLE IF NOT EXISTS `ql_registration_batch` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `submitted_by_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `source` varchar(32) NOT NULL,
  `client_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `participant_count` smallint unsigned NOT NULL DEFAULT 1,
  `submitted_at` datetime(3) NOT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_reg_batch_request` (`source`,`client_request_id`),
  KEY `idx_ql_reg_batch_session` (`session_id`,`submitted_at`),
  CONSTRAINT `fk_ql_reg_batch_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_reg_batch_submitter` FOREIGN KEY (`submitted_by_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_reg_batch_source` CHECK (`source` IN ('mini_program','web_admin','mobile_h5','legacy_excel','manual','other')),
  CONSTRAINT `ck_ql_reg_batch_count` CHECK (`participant_count` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='一次提交可包含多名独立报名参与者';

CREATE TABLE IF NOT EXISTS `ql_registration` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `batch_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `registration_status` varchar(24) NOT NULL DEFAULT 'pending',
  `payment_status` varchar(24) NOT NULL DEFAULT 'unpaid',
  `registration_source` varchar(32) NOT NULL,
  `registered_at` datetime(3) NOT NULL,
  `confirmed_at` datetime(3) DEFAULT NULL,
  `confirmed_by` bigint DEFAULT NULL,
  `session_referrer_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `return_primary_trigger` varchar(32) DEFAULT NULL,
  `return_trigger_note` varchar(500) DEFAULT NULL,
  `attribution_source` varchar(32) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `revision` int NOT NULL DEFAULT 0,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `cancelled_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_registration_customer_session` (`customer_id`,`session_id`),
  KEY `idx_ql_registration_session_status` (`session_id`,`registration_status`,`payment_status`),
  KEY `idx_ql_registration_batch` (`batch_id`),
  CONSTRAINT `fk_ql_registration_batch` FOREIGN KEY (`batch_id`) REFERENCES `ql_registration_batch` (`id`),
  CONSTRAINT `fk_ql_registration_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_registration_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_registration_session_referrer` FOREIGN KEY (`session_referrer_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_registration_status` CHECK (`registration_status` IN ('draft','pending','confirmed','waitlisted','cancelled','rescheduled')),
  CONSTRAINT `ck_ql_registration_payment` CHECK (`payment_status` IN ('unpaid','pending_confirmation','paid','refunded','waived')),
  CONSTRAINT `ck_ql_registration_source` CHECK (`registration_source` IN ('mini_program','web_admin','mobile_h5','legacy_excel','manual','other'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报名事实；报名状态与付款状态独立';

CREATE TABLE IF NOT EXISTS `ql_registration_status_log` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `registration_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status_type` varchar(24) NOT NULL,
  `from_status` varchar(24) DEFAULT NULL,
  `to_status` varchar(24) NOT NULL,
  `change_reason` varchar(500) DEFAULT NULL,
  `operator_id` bigint NOT NULL,
  `changed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_reg_status_registration` (`registration_id`,`changed_at`),
  CONSTRAINT `fk_ql_reg_status_registration` FOREIGN KEY (`registration_id`) REFERENCES `ql_registration` (`id`),
  CONSTRAINT `fk_ql_reg_status_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_reg_status_type` CHECK (`status_type` IN ('registration','payment'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报名及人工付款状态的不可变更历史';

CREATE TABLE IF NOT EXISTS `ql_participation` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `registration_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `attendance_status` varchar(24) NOT NULL DEFAULT 'not_arrived',
  `checked_in_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_participation_customer_session` (`customer_id`,`session_id`),
  KEY `idx_ql_participation_session_status` (`session_id`,`attendance_status`),
  CONSTRAINT `fk_ql_participation_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_participation_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_participation_registration` FOREIGN KEY (`registration_id`) REFERENCES `ql_registration` (`id`),
  CONSTRAINT `ck_ql_participation_status` CHECK (`attendance_status` IN ('not_arrived','checked_in','late','absent','left_early','completed','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每位轻友每期一条参与事实';

CREATE TABLE IF NOT EXISTS `ql_transaction` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `registration_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `transaction_type` varchar(24) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `payment_method` varchar(24) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'pending_confirmation',
  `transaction_at` datetime(3) NOT NULL,
  `record_source` varchar(32) NOT NULL,
  `external_transaction_no` varchar(100) DEFAULT NULL,
  `operator_id` bigint DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `revision` int NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_transaction_external_no` (`external_transaction_no`),
  KEY `idx_ql_transaction_customer_time` (`customer_id`,`transaction_at`),
  KEY `idx_ql_transaction_registration` (`registration_id`,`status`),
  KEY `idx_ql_transaction_session` (`session_id`,`status`),
  CONSTRAINT `fk_ql_transaction_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_transaction_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_transaction_registration` FOREIGN KEY (`registration_id`) REFERENCES `ql_registration` (`id`),
  CONSTRAINT `fk_ql_transaction_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_transaction_amount` CHECK (`amount` >= 0),
  CONSTRAINT `ck_ql_transaction_type` CHECK (`transaction_type` IN ('session','product','membership','digital','other')),
  CONSTRAINT `ck_ql_transaction_method` CHECK (`payment_method` IN ('cash','wechat_scan','alipay_scan','transfer','other','waived')),
  CONSTRAINT `ck_ql_transaction_status` CHECK (`status` IN ('pending_confirmation','paid','failed','refund_pending','refunded','cancelled')),
  CONSTRAINT `ck_ql_transaction_source` CHECK (`record_source` IN ('operator_entry','online_callback','legacy_excel','import','system')),
  CONSTRAINT `ck_ql_transaction_offline_operator` CHECK (`record_source` <> 'operator_entry' OR `operator_id` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='真实交易事实；当前主要由运营录入线下付款';

CREATE TABLE IF NOT EXISTS `ql_transaction_status_log` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `transaction_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `from_status` varchar(24) DEFAULT NULL,
  `to_status` varchar(24) NOT NULL,
  `change_reason` varchar(500) DEFAULT NULL,
  `operator_id` bigint NOT NULL,
  `changed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_tx_status_transaction` (`transaction_id`,`changed_at`),
  CONSTRAINT `fk_ql_tx_status_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `ql_transaction` (`id`),
  CONSTRAINT `fk_ql_tx_status_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易状态历史；撤销已付款必须保留原因';

CREATE TABLE IF NOT EXISTS `ql_interaction` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `channel` varchar(24) NOT NULL,
  `input_type` varchar(24) NOT NULL,
  `content_type` varchar(32) NOT NULL DEFAULT 'staff_observation',
  `summary` text,
  `occurred_at` datetime(3) NOT NULL,
  `confirmation_status` varchar(24) NOT NULL DEFAULT 'draft',
  `visibility_scope` varchar(24) NOT NULL DEFAULT 'internal',
  `sensitivity_level` tinyint unsigned NOT NULL DEFAULT 0,
  `operator_id` bigint DEFAULT NULL,
  `source` varchar(32) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_interaction_customer_time` (`customer_id`,`occurred_at`),
  KEY `idx_ql_interaction_session` (`session_id`,`occurred_at`),
  CONSTRAINT `fk_ql_interaction_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_interaction_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_interaction_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_interaction_channel` CHECK (`channel` IN ('wechat','phone','offline','voice_note','mini_program','system','other')),
  CONSTRAINT `ck_ql_interaction_input` CHECK (`input_type` IN ('text','audio','image','file','system_event')),
  CONSTRAINT `ck_ql_interaction_content` CHECK (`content_type` IN ('customer_statement','objective_fact','staff_observation','staff_judgement','ai_suggestion')),
  CONSTRAINT `ck_ql_interaction_confirm` CHECK (`confirmation_status` IN ('draft','pending_confirmation','confirmed','rejected')),
  CONSTRAINT `ck_ql_interaction_sensitivity` CHECK (`sensitivity_level` BETWEEN 0 AND 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='沟通、服务与历史健康备注的分层事实记录';

CREATE TABLE IF NOT EXISTS `ql_attachment` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `interaction_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `oss_id` bigint DEFAULT NULL,
  `original_name` varchar(255) NOT NULL,
  `mime_type` varchar(100) NOT NULL,
  `size_bytes` bigint unsigned NOT NULL,
  `sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `visibility_scope` varchar(24) NOT NULL DEFAULT 'internal',
  `sensitivity_level` tinyint unsigned NOT NULL DEFAULT 0,
  `scan_status` varchar(24) NOT NULL DEFAULT 'pending',
  `retention_until` date DEFAULT NULL,
  `uploaded_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_attachment_customer` (`customer_id`,`created_at`),
  KEY `idx_ql_attachment_hash` (`sha256`),
  CONSTRAINT `fk_ql_attachment_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_attachment_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_attachment_interaction` FOREIGN KEY (`interaction_id`) REFERENCES `ql_interaction` (`id`),
  CONSTRAINT `fk_ql_attachment_oss` FOREIGN KEY (`oss_id`) REFERENCES `sys_oss` (`oss_id`),
  CONSTRAINT `fk_ql_attachment_uploader` FOREIGN KEY (`uploaded_by`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_attachment_size` CHECK (`size_bytes` > 0),
  CONSTRAINT `ck_ql_attachment_scan` CHECK (`scan_status` IN ('pending','clean','blocked','failed')),
  CONSTRAINT `ck_ql_attachment_sensitivity` CHECK (`sensitivity_level` BETWEEN 0 AND 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='受控附件元数据；文件本体沿用 OSS';

CREATE TABLE IF NOT EXISTS `ql_follow_up_task` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `source_interaction_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `task_type` varchar(32) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'pending',
  `priority` varchar(16) NOT NULL DEFAULT 'normal',
  `assignee_user_id` bigint NOT NULL,
  `due_at` datetime(3) DEFAULT NULL,
  `result` varchar(1000) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_task_assignee_status` (`assignee_user_id`,`status`,`due_at`),
  KEY `idx_ql_task_customer` (`customer_id`,`created_at`),
  CONSTRAINT `fk_ql_task_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_task_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_task_interaction` FOREIGN KEY (`source_interaction_id`) REFERENCES `ql_interaction` (`id`),
  CONSTRAINT `fk_ql_task_assignee` FOREIGN KEY (`assignee_user_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_task_status` CHECK (`status` IN ('pending','in_progress','completed','skipped','failed','closed')),
  CONSTRAINT `ck_ql_task_priority` CHECK (`priority` IN ('low','normal','high','urgent'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='回访与运营待办';

CREATE TABLE IF NOT EXISTS `ql_pass_account` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `pass_type` varchar(50) NOT NULL,
  `valid_from` date DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_pass_customer` (`customer_id`,`status`),
  CONSTRAINT `fk_ql_pass_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_pass_dates` CHECK (`valid_until` IS NULL OR `valid_from` IS NULL OR `valid_until` >= `valid_from`),
  CONSTRAINT `ck_ql_pass_status` CHECK (`status` IN ('active','expired','void'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='卡次账户；余额由流水汇总';

CREATE TABLE IF NOT EXISTS `ql_pass_ledger` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `pass_account_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `transaction_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `entry_type` varchar(24) NOT NULL,
  `quantity_delta` int NOT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `operator_id` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_pass_ledger_account` (`pass_account_id`,`occurred_at`),
  CONSTRAINT `fk_ql_pass_ledger_account` FOREIGN KEY (`pass_account_id`) REFERENCES `ql_pass_account` (`id`),
  CONSTRAINT `fk_ql_pass_ledger_session` FOREIGN KEY (`session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_pass_ledger_transaction` FOREIGN KEY (`transaction_id`) REFERENCES `ql_transaction` (`id`),
  CONSTRAINT `fk_ql_pass_ledger_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_pass_ledger_type` CHECK (`entry_type` IN ('grant','consume','adjust','expire','void','refund')),
  CONSTRAINT `ck_ql_pass_ledger_nonzero` CHECK (`quantity_delta` <> 0),
  CONSTRAINT `ck_ql_pass_consume_session` CHECK (`entry_type` <> 'consume' OR `session_id` IS NOT NULL),
  CONSTRAINT `ck_ql_pass_adjust_reason` CHECK (`entry_type` <> 'adjust' OR (`reason` IS NOT NULL AND CHAR_LENGTH(TRIM(`reason`)) > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可直接覆盖的卡次流水';

CREATE TABLE IF NOT EXISTS `ql_consent_record` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `consent_type` varchar(32) NOT NULL,
  `status` varchar(16) NOT NULL,
  `policy_version` varchar(32) NOT NULL,
  `granted_at` datetime(3) DEFAULT NULL,
  `withdrawn_at` datetime(3) DEFAULT NULL,
  `source` varchar(32) NOT NULL,
  `evidence_attachment_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `recorded_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_consent_customer_type` (`customer_id`,`consent_type`,`created_at`),
  CONSTRAINT `fk_ql_consent_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_consent_attachment` FOREIGN KEY (`evidence_attachment_id`) REFERENCES `ql_attachment` (`id`),
  CONSTRAINT `fk_ql_consent_recorder` FOREIGN KEY (`recorded_by`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_consent_type` CHECK (`consent_type` IN ('service_required','operations_contact','ai_processing','anonymized_research','brand_reuse')),
  CONSTRAINT `ck_ql_consent_status` CHECK (`status` IN ('granted','denied','withdrawn','expired'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='分用途、分版本的授权记录';

CREATE TABLE IF NOT EXISTS `ql_import_batch` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_file_name` varchar(255) NOT NULL,
  `source_file_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sheet_name` varchar(100) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'uploaded',
  `total_rows` int unsigned NOT NULL DEFAULT 0,
  `inserted_rows` int unsigned NOT NULL DEFAULT 0,
  `matched_rows` int unsigned NOT NULL DEFAULT 0,
  `conflict_rows` int unsigned NOT NULL DEFAULT 0,
  `failed_rows` int unsigned NOT NULL DEFAULT 0,
  `uploaded_by` bigint NOT NULL,
  `uploaded_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` datetime(3) DEFAULT NULL,
  `raw_retention_until` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_import_source` (`source_file_sha256`,`sheet_name`),
  CONSTRAINT `fk_ql_import_uploader` FOREIGN KEY (`uploaded_by`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_import_status` CHECK (`status` IN ('uploaded','validating','ready','importing','completed','failed','cancelled')),
  CONSTRAINT `ck_ql_import_counts` CHECK (`inserted_rows` + `matched_rows` + `conflict_rows` + `failed_rows` <= `total_rows`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='历史 Excel 导入批次';

CREATE TABLE IF NOT EXISTS `ql_import_row` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `batch_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_row_number` int unsigned NOT NULL,
  `source_payload` json NOT NULL,
  `normalized_payload` json DEFAULT NULL,
  `row_status` varchar(24) NOT NULL DEFAULT 'pending',
  `matched_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `matched_session_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_registration_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `processed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_import_row` (`batch_id`,`source_row_number`),
  KEY `idx_ql_import_row_status` (`batch_id`,`row_status`),
  CONSTRAINT `fk_ql_import_row_batch` FOREIGN KEY (`batch_id`) REFERENCES `ql_import_batch` (`id`),
  CONSTRAINT `fk_ql_import_row_customer` FOREIGN KEY (`matched_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_import_row_session` FOREIGN KEY (`matched_session_id`) REFERENCES `ql_session` (`id`),
  CONSTRAINT `fk_ql_import_row_registration` FOREIGN KEY (`created_registration_id`) REFERENCES `ql_registration` (`id`),
  CONSTRAINT `ck_ql_import_row_status` CHECK (`row_status` IN ('pending','valid','matched','inserted','conflict','failed','ignored'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='导入逐行结果；原始敏感值受限访问并按批次到期清理';

CREATE TABLE IF NOT EXISTS `ql_merge_candidate` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_a_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `customer_b_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `evidence_json` json NOT NULL,
  `conflict_fields_json` json DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'pending_review',
  `decision` varchar(24) DEFAULT NULL,
  `reviewed_by` bigint DEFAULT NULL,
  `reviewed_at` datetime(3) DEFAULT NULL,
  `decision_reason` varchar(500) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ql_merge_pair` (`customer_a_id`,`customer_b_id`),
  KEY `idx_ql_merge_status` (`status`,`created_at`),
  CONSTRAINT `fk_ql_merge_customer_a` FOREIGN KEY (`customer_a_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_merge_customer_b` FOREIGN KEY (`customer_b_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_merge_reviewer` FOREIGN KEY (`reviewed_by`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_merge_order` CHECK (`customer_a_id` < `customer_b_id`),
  CONSTRAINT `ck_ql_merge_status` CHECK (`status` IN ('pending_review','reviewing','resolved','dismissed')),
  CONSTRAINT `ck_ql_merge_decision` CHECK (`decision` IS NULL OR `decision` IN ('merge_a_into_b','merge_b_into_a','keep_separate'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='疑似重复主档候选；只允许人工决定';

CREATE TABLE IF NOT EXISTS `ql_ai_processing_run` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `interaction_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `purpose` varchar(50) NOT NULL,
  `provider` varchar(50) NOT NULL,
  `model` varchar(100) NOT NULL,
  `prompt_version` varchar(32) NOT NULL,
  `input_scope_json` json NOT NULL,
  `output_json` json DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'pending',
  `human_decision` varchar(24) DEFAULT NULL,
  `confirmed_by` bigint DEFAULT NULL,
  `confirmed_at` datetime(3) DEFAULT NULL,
  `latency_ms` int unsigned DEFAULT NULL,
  `input_tokens` int unsigned DEFAULT NULL,
  `output_tokens` int unsigned DEFAULT NULL,
  `cost_amount` decimal(12,6) DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_ai_customer_time` (`customer_id`,`created_at`),
  KEY `idx_ql_ai_status` (`status`,`created_at`),
  CONSTRAINT `fk_ql_ai_interaction` FOREIGN KEY (`interaction_id`) REFERENCES `ql_interaction` (`id`),
  CONSTRAINT `fk_ql_ai_customer` FOREIGN KEY (`customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `fk_ql_ai_confirmer` FOREIGN KEY (`confirmed_by`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `ck_ql_ai_status` CHECK (`status` IN ('pending','processing','pending_confirmation','confirmed','failed','abandoned')),
  CONSTRAINT `ck_ql_ai_decision` CHECK (`human_decision` IS NULL OR `human_decision` IN ('accepted','edited','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI 调用审计；不得保存服务密钥';

CREATE TABLE IF NOT EXISTS `ql_audit_log` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `actor_user_id` bigint DEFAULT NULL,
  `actor_customer_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `client_type` varchar(24) NOT NULL,
  `action` varchar(64) NOT NULL,
  `object_type` varchar(64) NOT NULL,
  `object_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `before_json` json DEFAULT NULL,
  `after_json` json DEFAULT NULL,
  `reason` varchar(500) DEFAULT NULL,
  `request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `ip_address` varchar(128) DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ql_audit_object` (`object_type`,`object_id`,`occurred_at`),
  KEY `idx_ql_audit_actor` (`actor_user_id`,`occurred_at`),
  CONSTRAINT `fk_ql_audit_user` FOREIGN KEY (`actor_user_id`) REFERENCES `sys_user` (`user_id`),
  CONSTRAINT `fk_ql_audit_customer` FOREIGN KEY (`actor_customer_id`) REFERENCES `ql_customer` (`id`),
  CONSTRAINT `ck_ql_audit_client` CHECK (`client_type` IN ('web_admin','mobile_h5','mini_program','system','import_job'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='关键业务操作审计；日志中应脱敏敏感字段';

INSERT INTO `ql_schema_migration` (`version`,`description`)
VALUES ('1.1.0','轻友统一档案、Session、报名、线下付款状态、运营记录与导入治理核心表')
ON DUPLICATE KEY UPDATE `description`=VALUES(`description`);
